### ISSUE TITLE
use buffer pool

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#103]

**Comment by rrybarczyk** [comment]
The Codec currently implements and exports the [`Buffer` trait](https://github.com/stratum-mining/stratum/blob/main/protocols/v2/codec-sv2/src/buffer.rs#L3).

It should instead import use and reexport the `Buffer` trait from [`buffer-pool`](https://github.com/stratum-mining/stratum/blob/main/utils/buffer/src/lib.rs#L61). Via a compile flag, we should instruct the codec to use the `Buffer` that is currently using either `SlowAndCorrect` or the one that is implemented in `buffer-pool` (that is faster but has some unsafe code). We should modify the `sv2-ffi` crate in order to use the codec with the `SlowAndCorrect` buffer, so at least at the beginning, we will use the safest implementation in Bitcoin Core.
