### ISSUE TITLE
Add `stop` function for roles

### ISSUE THREAD

**Issue by jbesraa** [stratum-mining/stratum#1148]
After merging #1092 #1095 and #1097 we would like to start completing #1066. One requirement we need is a function to terminate a role, for example for `PoolSV2` we need to add `PoolSV2::stop`. Any ideas on how best to approach this would be appreciated!

**Comment by plebhash** [comment]
@jbesraa can you elaborate on the motivations for this?

what kind of scenario are we trying to mitigate?

**Comment by plebhash** [comment]
overall, we should be as conservative as possible, because otherwise we will start going down very deep rabbit holes

I was originally excited about #1120 because it felt like a low-hanging-fruit that would allow us to migrate our CI away from MG and patch bugs on the PoC `roles` in a more sustainable and scalable way on the near future

but if this task will impose the need for deep refactors into the `roles`, then the trade-offs are no longer worth it in my view

**Comment by GitGab19** [comment]
Hey @jbesraa did you find a workaround for this?
Have you explored the task collector option suggested by @Shourya742 last call?

**Comment by Shourya742** [comment]
@GitGab19 I am seeing new changes here: https://github.com/stratum-mining/stratum/pull/1066. @jbesraa has introduced state machine in roles crate. I am not very certain why this approach is taken, as in one of the meetings it was decided to not add code specific to integration test suite in production code. But I guess thats the workaround, rather than killing the joinhandles.

**Comment by jbesraa** [comment]
I am closing this as its irrelevant atm. please move the discussion to #1066
