### ISSUE TITLE
`mining-device` cpu miner does not hit the target

### ISSUE THREAD

**Issue by jbesraa** [stratum-mining/stratum#1188]
When running the `mining-device` locally I was not able to hit the `target` set here https://github.com/stratum-mining/stratum/blob/main/roles/test-utils/mining-device/src/lib/mod.rs#L201

The test was not run for too long, probably for a couple of minutes. While in practice that might not be a problem, in test environment we want shares to be submitted in a matter of seconds in order to not run the test for too long.

**Comment by GitGab19** [comment]
Also, I noticed we are multiplying the target with the number of threads here: https://github.com/stratum-mining/stratum/blob/c05d8cd3f02346931bbaefdb00d3413c757294e1/roles/test-utils/mining-device/src/lib/mod.rs#L200-L201.
I don't think it's correct (cc @Fi3).

If you agree on both removing this, and adding the parameter I was mentioning, I can open a PR to fix this, so unblocks the integration test @jbesraa is writing

**Comment by GitGab19** [comment]
Yes, but the measure_hashrate function computes the hashrate of the entire machine, how does it relate to the number of cores?

**Comment by GitGab19** [comment]
I see, but I still don't get why there's the `-3` into the `p` computation.
However, my proposal to add an extra optional argument (the `divisor`) still remains.

**Comment by plebhash** [comment]
porting over from https://github.com/stratum-mining/stratum/pull/1066#discussion_r1788088738

once we fix this issue with `mining-device`, we should have the following integration test:

- start TP
- start Pool (connected to TP)
- start SV2 CPU Miner (connected to Pool)

we can assert that:
- Pool connects to TP and receives template (basically what's already being done on `success_pool_template_provider_connection`)
- SV2 CPU Miner connects to Pool (`SetupConnection` / `SetupConnection.Success`)
- SV2 CPU Miner opens standard channel with Pool (`OpenStandardMiningChannel` / `OpenStandardMiningChannel.Success`)
- Pool sends `SetTarget` to SV2 CPU Miner (`SetTarget`)
- Pool sends Standard Job to SV2 CPU Miner (`NewMiningJob`)
- SV2 CPU Miner sends share to Pool (`SubmitSharesStandard`)
- Pool confirms receiving share (`SubmitShares.Success`)

we can assert things like channel ids and job ids

**Comment by GitGab19** [comment]
> I think the best way to manage this would be something like this: <img alt="Screenshot 2024-10-07 at 17 38 33" width="878" src="https://private-user-images.githubusercontent.com/62447440/374238175-f7b914d0-fbd0-416a-a529-0c91ddb94c91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDAyNDQsIm5iZiI6MTcyODM5OTk0NCwicGF0aCI6Ii82MjQ0NzQ0MC8zNzQyMzgxNzUtZjdiOTE0ZDAtZmJkMC00MTZhLWE1MjktMGM5MWRkYjk0YzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE1MDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOTY0ZWI1ZmE0MDk0ZjAxM2NlZjY4NjcwNmMxMjkxM2VjNmI4NmI1YmIxYzYzY2E1MmU1N2EwNDRlZDNmMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UEtg438UapTMoqRo_VKfmKCHr2XljKDUwhQx93Lw_U4"> We can take the `divisor` as an optional argument passed in the command to run the miner. In this way you can decide how much easier your jobs will be.

@Fi3 @jbesraa any feedback on this?

**Comment by plebhash** [comment]
@Fi3 one question that remains unanswered:

https://github.com/stratum-mining/stratum/blob/c05d8cd3f02346931bbaefdb00d3413c757294e1/roles/test-utils/mining-device/src/lib/mod.rs#L200

why are we substracting 3 here?

**Comment by plebhash** [comment]
@GitGab19 what if instead of adding yet a new CLI arg `divisor`, we just leverage `handicap`?

it serves a very similar purpose

`handicap` is not taken into consideration on `measure_hashrate`, so we would need to include that

(tbh I think `handicap` should be an input for `measure_hashrate` independently of the discussion we're having here, since otherwise `measure_hashrate` will report inaccurate info)

**Comment by plebhash** [comment]
> > I think the best way to manage this would be something like this: <img alt="Screenshot 2024-10-07 at 17 38 33" width="878" src="https://private-user-images.githubusercontent.com/62447440/374238175-f7b914d0-fbd0-416a-a529-0c91ddb94c91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDAyNDQsIm5iZiI6MTcyODM5OTk0NCwicGF0aCI6Ii82MjQ0NzQ0MC8zNzQyMzgxNzUtZjdiOTE0ZDAtZmJkMC00MTZhLWE1MjktMGM5MWRkYjk0YzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE1MDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOTY0ZWI1ZmE0MDk0ZjAxM2NlZjY4NjcwNmMxMjkxM2VjNmI4NmI1YmIxYzYzY2E1MmU1N2EwNDRlZDNmMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UEtg438UapTMoqRo_VKfmKCHr2XljKDUwhQx93Lw_U4"> We can take the `divisor` as an optional argument passed in the command to run the miner. In this way you can decide how much easier your jobs will be.
> 
> @Fi3 @jbesraa any feedback on this?

I think there's a simpler way to solve this problem

instead of adding yet a new CLI arg `divisor`, we can simply leverage another one that already exists: `handicap`

`handicap` already serves a very similar purpose, the only difference is that it's not yet being taken into account on `measure_hashrate`

(tbh I think `handicap` should be an input for `measure_hashrate` independently of the discussion we're having here, since otherwise `measure_hashrate` will report inaccurate info and result in bad channels)

---

@jbesraa please cherry pick this commit and see if that unblocks the test you were trying to write:

https://github.com/plebhash/stratum/commit/c217b8c3103bbba76fcb53b7060b12f7366a919d

**Comment by plebhash** [comment]
> > I think the best way to manage this would be something like this: <img alt="Screenshot 2024-10-07 at 17 38 33" width="878" src="https://private-user-images.githubusercontent.com/62447440/374238175-f7b914d0-fbd0-416a-a529-0c91ddb94c91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDAyNDQsIm5iZiI6MTcyODM5OTk0NCwicGF0aCI6Ii82MjQ0NzQ0MC8zNzQyMzgxNzUtZjdiOTE0ZDAtZmJkMC00MTZhLWE1MjktMGM5MWRkYjk0YzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE1MDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOTY0ZWI1ZmE0MDk0ZjAxM2NlZjY4NjcwNmMxMjkxM2VjNmI4NmI1YmIxYzYzY2E1MmU1N2EwNDRlZDNmMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UEtg438UapTMoqRo_VKfmKCHr2XljKDUwhQx93Lw_U4"> We can take the `divisor` as an optional argument passed in the command to run the miner. In this way you can decide how much easier your jobs will be.
> 
> @Fi3 @jbesraa any feedback on this?

I thought about an alternative:

instead of `divisor` CLI arg, we could add `advertise_hashrate`, where we essentially choose which hashrate we want this CPU miner to advertise while opening channels

this would be an optional CLI arg, and when left empty, the SV2 CPU miner would simply advertise the measured hashrate

the usage of `advertise_hashrate` would allow us to test some DoS vectors, since it would allow the user to say they have a very small hashrate and later spam the upstream with low difficulty shares

**Comment by plebhash** [comment]
while research for the idea I described above, I noticed that `measure_hashrate` is not taking `handicap` into consideration

that is a problem, independently of the discussion we're having here

if `handicap` bigger than`0`, then `measure_hashrate` must take that into consideration, otherwise it will report something that is not accurate

**Comment by GitGab19** [comment]
I don't think it's the reason behind handicap. Here's the description from the README: "This value is used to slow down the cpu miner, it represents the number of micro-seconds that are awaited between hashes [default: 0]".
I still don't know the reason why it was introduced, but it seems to be it's a way to slow down the mining-device

**Comment by plebhash** [comment]
> I don't think it's the reason behind handicap. Here's the description from the README: "This value is used to slow down the cpu miner, it represents the number of micro-seconds that are awaited between hashes [default: 0]". I still don't know the reason why it was introduced, but it seems to be just a way to slow down the mining-device

if `handicap` is `0`, the CPU miner uses the maximum available hashpower on the system

if `handicap` is bigger than `0`, the CPU miner uses less than the max hashpower

so it feels reasonable that `handicap` is reflected on `measure_hashrate`, because it has a direct impact in the CPU miner hashpower
