### ISSUE TITLE
No Serder codec can not parse struct with docs comment

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#22]
The derive macros that parse struct [decodable](https://github.com/stratum-mining/stratum/blob/main/protocols/v2/binary-sv2/no-serde-sv2/derive_codec/src/lib.rs#L220) and [encodable](https://github.com/stratum-mining/stratum/blob/main/protocols/v2/binary-sv2/no-serde-sv2/derive_codec/src/lib.rs#L306) should remove every doc comment from the token stream before to parse it.

**Comment by ccdle12** [comment]
I think this is already addressed by [remove_attributes()?](https://github.com/stratum-mining/stratum/blob/main/protocols/v2/binary-sv2/no-serde-sv2/derive_codec/src/lib.rs#L13) 

It looks like it will capture doc comments above structs since the `TokenTree::Punct` for doc comments will be interpreted as 
`#[doc_comment(...)]`
