### ISSUE TITLE
Bump `rustc`:

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratum#548]
**_Originally posted by Fi3_**

Whenever we have it on stable https://blog.rust-lang.org/inside-rust/2022/11/17/async-fn-in-trait-nightly.html bump rustc version for SRI and remove the async trait dep

https://blog.rust-lang.org/inside-rust/2023/05/03/stabilizing-async-fn-in-trait.html

**Comment by moneyball** [comment]
What is this project's MSRV policy? Other projects in the Rust bitcoin ecosystem are at various stages of maturity thinking about this, but I think it is good to have clarity.

**Comment by Fi3** [comment]
In the past we had a limitation due to max rustc version buildable with guix, but now that we decided to implement the template provider in bitcoind in c++ and not rust we do not have it anymore. So for now not MSRV policy , having async trait would greatly improve SRI codebase so I would say that if 1.74 will have it, we should depend at minimum on 1.74.

**Comment by Fi3** [comment]
Now we use 1.65:
```toml
[toolchain]
channel = "1.65.0"
components = [ "rustfmt", "clippy" ]
profile = "minimal"
```
given that the project is still in a early phase and that "native" async trait is a not negligible cause we use async traits in a lot of places,  I personally would prefer to wait fo3 1.74.

**Comment by Fi3** [comment]
https://github.com/stratum-mining/stratum/pull/710/files
