### ISSUE TITLE
cannot connect to any of the Template Provider (testnet or regtest), 

### ISSUE THREAD

**Issue by hdlslm** [stratum-mining/stratum#713]
testnet times out: ERROR pool_sv2: Could not connect to Template Provider: I/O error: `Os { code: 110, kind: TimedOut, message: "Connection timed out" }

&& ||

regtest seems to connect: INFO pool_sv2::lib::template_receiver: Connected to template distribution server at 75.119.150.111:8442
but errors out w/: ERROR network_helpers::plain_connection_tokio: Failed to read from stream: early eof
ERROR pool_sv2: Could not connect to Template Provider: Channel recv failed: `RecvError`

running latest ubuntu server vm on proxmox, turned off router firewall and tried, received same errors. ufw is inactive on the os level. is there anything else i could check. thanks

**Comment by GitGab19** [comment]
> testnet times out: ERROR pool_sv2: Could not connect to Template Provider: I/O error: `Os { code: 110, kind: TimedOut, message: "Connection timed out" }
> 
> && ||
> 
> regtest seems to connect: INFO pool_sv2::lib::template_receiver: Connected to template distribution server at 75.119.150.111:8442 but errors out w/: ERROR network_helpers::plain_connection_tokio: Failed to read from stream: early eof ERROR pool_sv2: Could not connect to Template Provider: Channel recv failed: `RecvError`
> 
> running latest ubuntu server vm on proxmox, turned off router firewall and tried, received same errors. ufw is inactive on the os level. is there anything else i could check. thanks

Are you following our `getting-started` guide on stratumprotocol.org, right?
We updated a lot of stuff during last months (all our development is on `dev` branch), and we also changed the server where we are hosting our Template Provider. Right now the `testnet` one is running at `75.119.150.111:8442`, so you should use this address in your config file.
However, since we are going to release a big update in the next weeks, you would encounter the problem you already saw, because the TP which is running at `75.119.150.111:8442` is ready for our next release (which changed lots of stuff in the handshake phase between Pool and TP as well).
For this reason you are not able to use our hosted TP with the **current** `main` branch. 

So there are some options:
- Run the TP locally (you can follow the guide on our website [here](https://stratumprotocol.org/getting-started/#1-install-setup-and-run-local-regtest-template-provider)
- Switch over dev branch and run the new stack
- Wait a week and the next getting-started guide will be published on our website, along with our next release
