### ISSUE TITLE
Move JDC initialization from `main` to `lib`

### ISSUE THREAD

**Issue by jbesraa** [stratum-mining/stratum#992]
I am trying to write some tests running the whole flow, and noticed that JDC initialization is happening inside `main.rs` rather than `lib.rs` which makes it not very modular. I propose to move the initialization to `lib` so it could be exported and used in different context, like testing

**Comment by Fi3** [comment]
whatever function will end up initializing the role should take async streams of messages not addresses

**Comment by jbesraa** [comment]
@Fi3 Could you please comment here https://github.com/stratum-mining/stratum/pull/993 with a bit more details?

**Comment by Fi3** [comment]
It was just a generic comment about make it more modular. Instead of open the socket on initialization, passing a stream of messages so we decouple actual role logic from tansport layer and encryption layer. This is useful for example if I want to initialize inside my application, and somewhere else in the application I already received and decrypted the messages. As I said above is a generic comment about this issue. Not sure if is suited for your PR or not.

**Comment by jbesraa** [comment]
Done at #993
